In [1]:
import numpy as np

**ONE DIMENSIONAL NUMPY ARRAY**

In [2]:
one = np.array([1,2,3])

***Checking Dimensions of Numpy Array***

In [3]:
one.ndim

1

**TWO DIMENSIONAL NUMPY ARRAY**

In [4]:
two = np.array([[1,2],[3,4]])

***Checking Dimensions of Numpy Array***

In [5]:
two.ndim

2

**Checking Memory Size of Array Elements**

In [6]:
one.itemsize

4

In [7]:
two.itemsize

4

**DType Property**

In [8]:
two.dtype

dtype('int32')

In [9]:
## To change the type of any we have to use dtype = np.type of datatype which we want.

In [10]:
a = np.array([[1,2],[3,4]])

In [11]:
a.dtype

dtype('int32')

In [12]:
a = np.array([[1,2],[3,4]], dtype = np.float64)

In [13]:
a.dtype

dtype('float64')

In [14]:
a

array([[1., 2.],
       [3., 4.]])

**SIZE PROPERTY**

In [15]:
## It is used to check the total number of elements in an numpy array.

In [16]:
s = np.array([[1,2],[3,4],[5,6]])

In [17]:
s.size

6

**SHAPE PROPERTY**

In [18]:
## Shape property is used to check the no of rows and columns in an array.

In [19]:
i = np.array([[1,2],[3,4],[5,6]])

In [20]:
i.shape

(3, 2)

**RESHAPE PROPERTY**

In [21]:
## Used to reshape an array

In [22]:
i.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
i.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

**RAVEL PROPERTY**

In [24]:
## Used for flattening an array.

In [25]:
i.ravel()

array([1, 2, 3, 4, 5, 6])

**ZEROS NUMPY PROPERTY**

In [26]:
## Used to create an array of zeros.

In [27]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**ONES NUMPY PROPERTY**

In [28]:
## Used to create an array of ones.

In [29]:
o = np.ones((3,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**RANGE FUNCTION**

In [30]:
## Used to create an array of given range.

In [31]:
r = np.arange(1,5)
r

array([1, 2, 3, 4])

In [32]:
w = np.arange(1,10,2)
w

array([1, 3, 5, 7, 9])

**LINSPACE FUNCTION**

In [33]:
## Used to create an array of same difference between given number range and no of elements specified.

In [34]:
l = np.linspace(1,5,10)
l

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

**MIN, MAX, SUM Type Functions**

In [35]:
a = np.arange(1,6)
b = np.arange(6,11)

In [36]:
a, b

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [37]:
a.min()

1

In [38]:
b.min()

6

In [39]:
a.max()

5

In [40]:
b.max()

10

In [41]:
a.sum()

15

In [42]:
b.sum()

40

In [43]:
a+b

array([ 7,  9, 11, 13, 15])

In [44]:
a-b

array([-5, -5, -5, -5, -5])

In [45]:
a*b

array([ 6, 14, 24, 36, 50])

In [46]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [47]:
## Axis = 0 (Column) ; Axis = 1 (Rows)

In [48]:
a.sum(axis=0)

15

In [49]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])

In [50]:
a

array([[1, 2],
       [3, 4]])

In [51]:
a.sum(axis = 0)

array([4, 6])

In [52]:
a.sum(axis = 1)

array([3, 7])

In [53]:
c = np.sqrt(a)
c

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [54]:
d = np.std(a)
d

1.118033988749895

In [55]:
a.dot(b)

array([[ 7, 10],
       [15, 22]])