**Intro of Numpy**

In [1]:
import sys

In [2]:
import time

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
a[0],a[1],a[2]

(1, 2, 3)

In [7]:
print(type(a))

<class 'numpy.ndarray'>


**Less Memory Feature of Numpy**

In [8]:
l = list(range(1000))

In [9]:
print(sys.getsizeof(1)*len(l))

28000


In [10]:
b = np.arange(1000)

In [11]:
print(b.itemsize * b.size)

4000


**Fast Computation Feature of Numpy**

In [12]:
size = 100000

In [13]:
l1 = range(size)
l2 = range(size)

In [14]:
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("Time taken in l1 + l2 = " , time.time() - start)

Time taken in l1 + l2 =  0.038574934005737305


In [15]:
a1 = np.arange(size)
a2 = np.arange(size)

In [16]:
start = time.time()
result = a1+a2
print("Time taken in a1 + a2 = " , time.time() - start)

Time taken in a1 + a2 =  0.007814645767211914


**Some Basic Operations**

In [17]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [18]:
a1+a2

array([5, 7, 9])

In [19]:
a1-a2

array([-3, -3, -3])

In [20]:
a1*a2

array([ 4, 10, 18])

In [21]:
a1/a2

array([0.25, 0.4 , 0.5 ])