## INDEXING IN NUMPY ARRAY

**ONE DIMENSIONAL ARRAY INDEXING**

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a[0]

1

In [4]:
a[0:5:2]

array([1, 3, 5])

In [5]:
a[-1]

5

In [6]:
a[-1]

5

**TWO DIMENSIONAL ARRAY INDEXING**

In [7]:
b = np.array([[1,2],[3,4],[5,6]])

In [8]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
b[0,1]

2

In [10]:
b[2,1]

6

In [11]:
b[0:3,1]

array([2, 4, 6])

In [12]:
b[-1]

array([5, 6])

**Flatting of array**

In [13]:
b = np.array([[1,2],[3,4],[5,6]])

In [14]:
for i in b.flat:
    print(i)

1
2
3
4
5
6


## Stacking and Splitting In Numpy Array

**Stacking**

In [15]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [16]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [18]:
c = np.vstack((a,b))

In [19]:
c

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
d = np.hstack((a,b))

In [21]:
d

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

**Splitting**

In [22]:
result = np.hsplit(d,2)
result

[array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]])]

In [23]:
result[0]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [24]:
result[1]

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
result = np.vsplit(d,3)
result

[array([[0, 1, 6, 7]]), array([[2, 3, 8, 9]]), array([[ 4,  5, 10, 11]])]

# BOOLEAN ARRAYS

In [26]:
a = np.arange(15).reshape(3,5)

In [27]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
b = a>5

In [29]:
b

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [30]:
a[b]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
a[b] = -1
a

array([[ 0,  1,  2,  3,  4],
       [ 5, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])